# .github/workflows/qa.yml
name: QA Pipeline

on:
  push:
    branches:
      - qa

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: npm install
      - name: Rodar testes
        run: npm test
